base_url = "https://blog.azmarach.work/"
title = "azmablog"
description = "Writing down my learning process. Probably mainly Rust, and Java..."
compile_sass = true
minify_html = true
# build_search_index = true
theme = "duckquill"
default_language = "en"
generate_feeds = true


[[taxonomies]]
name = "tags"
# feed = true

[markdown]
highlight_code = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
github_alerts = true

[extra]
author = "Jan Charamza"
main_site_url = "https://azmarach.work"
emoji_favicon = "🦀"
accent_color = "#9d4edd"
accent_color_dark = "#c77dff"
default_theme = "auto"
styles = ["custom.css"]
show_reading_time = true
show_copy_button = true

[extra.footer]
show_copyright = true
show_source = true
show_powered_by = true

# copyright = "© 2025 Jan Charamza — All rights reserved."


# Source URL for repository link (optional)
# source_url = "https://github.com/charamzic/azmaweb"

# Navigation configuration
[extra.nav]
show_theme_switcher = true
# show_feed = true
# show_repo = true

# Navigation links - THIS IS THE KEY PART
[[extra.nav.links]]
name = "Posts"
url = "posts"

[[extra.nav.links]]
name = "Code"
url = "code"

# Social links in footer (optional)
[[extra.social]]
name = "GitHub"
url = "https://github.com/charamzic/azmaweb"
icon = "github"
